### ISSUE TITLE
[TODO] Some bugs and refactor for handling POST request

### ISSUE THREAD

**Issue by LeaYeh** [LeaYeh/webserver#113]
1. [x] - in _process the analyzer already make sure the `Except` header must be 100, dont need to check again
2. [x] -  access F_OK and W_OK should separate for not found and forbidden
3. [x] -  all of the header key should consistent to be lower case
4. [x] -  change ofstream from * to &
5. [x] -  use std::remove and std::rename to fit the subject

**Comment by LeaYeh** [comment]
2024-12-09 22:40:09 [DEBUG] ConnectionHandler::handleEvent() on fd: 6 with events: EPOLLIN EPOLLOUT                             
2024-12-09 22:40:09 [DEBUG] Received events: EPOLLIN EPOLLOUT  on fd: 6                                                         
2024-12-09 22:40:09 [DEBUG] Read content: 
2 1]>>stream␍
h�bbd``b`�
$�@��`�$xb���x1����k9����H����o��       ␍
startxref␍


@Leske the issue is from kernel and quite critical, we use state to control the flow but if EPOLLIN EPOLLOUT comming at same time and POST is still handling. then the analyzer need to be trigger for the EPOLLIN but now the body is still processing

**Comment by LeaYeh** [comment]
```
Hey I think maybe we thinking too complicated
For a connection we won’t support pipeing so if a request not finished we should not handle EPOLLIN
maybe the right behavior should be if the sth is processing we should turn off the EPOLLIN monitor
```
