### ISSUE TITLE
[TODO] Possible status with different method

### ISSUE THREAD

**Issue by LeaYeh** [LeaYeh/webserver#50]
GENERAL
- [ ] if exceptions happen the server should not just shutdown but return `500 Internal Server Error` for debugging or monitor
- [ ] if the server overloading or handle to many requests, the server could return `503 Service Unavailable` with `Retry-After: 120`
- [ ] (bonus) `401 Unauthorized` and `403 Forbidden` about login and session

GET 
- [ ] Range Requests: When the user tries to request a huge file, to avoid retry to download the whole file from begin the client will setup `Range: bytes=100000000-` in header and the server will response the correspond part with the status code `206 Partial Content`
- [ ] Handle redirect by location config, `301 Moved Permanently` 
- [ ] The client may request to check the cache by `If-Modified-Since` or `ETag`, should return `304 Not Modified`
- [ ] If the resource does not exist then return `404 Not Found`
- [ ] If the request method is not allowed with the config then return `405 Method Not Allowed`
- [ ] if the respond file format is not match the `content-type` then return `406 Not Acceptable`

POST and PUT
- [ ] -When the client tries to update a large file but it can not upload the whole file in time then timeout, need to return `408 Request Timeout`

**Comment by LeaYeh** [comment]
@yenthing 

Consider the `RFC7230`

```
An HTTP/1.1 message can be made up of many different headers and can be sent using various methods. The message should be processed according to the specification for each header field.
```

And the `RFC7231`

```
HTTP/1.1 provides a mechanism to extend the protocol with new header fields. Extensions should be done in a way that does not break the existing functionality of the protocol.
```

I will suggest all the headers should be stored in variable and the kernel side will handle it or just ignore it.
