### ISSUE TITLE
[TODO] Possible status when analyze a request

### ISSUE THREAD

**Issue by LeaYeh** [LeaYeh/webserver#52]
- [ ] According to the `RFC7230` and `RFC7231` the header field can be very flexible so the analyzer should record all the header fields
- [ ] For the security consideration, not clear define in RFC but can easy crash our web server, add limitation of header size is needed `431 Request Header Fields Too Large`, need to handle it with config `client_max_body_size` or add a new one.
- [ ] when the header setup `Transfer-Encoding:chunked` the analyzer needs to check the format is valid or not
    - It's not part of state machine, needs to export a new function

**Comment by LeaYeh** [comment]
Consider the `RFC7230`

```
An HTTP/1.1 message can be made up of many different headers and can be sent using various methods. The message should be processed according to the specification for each header field.
```

And the `RFC7231`

```
HTTP/1.1 provides a mechanism to extend the protocol with new header fields. Extensions should be done in a way that does not break the existing functionality of the protocol.
```

I will suggest all the headers should be stored in variable and the kernel side will decide to handle it or just ignore it.

_Originally posted by @LeaYeh in https://github.com/LeaYeh/webserver/issues/50#issuecomment-2351095056_
